[package]
name = "watch-config"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1.7"
directories = "6"
notify = "8"
notify-debouncer-full = "0.5"
schematic = { version = "0.18", features = [
  "schema",
  "renderer_template",
  "json",
  "pkl",
  "toml",
  "yaml",
] }
serde = "1.0.134"
tokio = { version = "1.27", features = ["rt", "sync", "macros"] }
tokio-util = "0.7.1"
tracing = "0.1"
futures-cancel = { git = "https://github.com/aschey/futures-cancel", rev = "d2c20b78ff5c9e85aa892b51971cc1c1b6b22351" }
edit = "0.1.5"
futures = "0.3.30"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread", "sync", "macros"] }
clap = { version = "4.5.31", features = ["derive"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
